version: "3.7"
services:
  app:
    build:
      args:
        user: Ruan
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: api-opovo
    container_name: jornalopovo-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - api-opovo

  db:
    image: mysql:5.7
    container_name: apiopovo-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - api-opovo

  nginx:
    image: nginx:alpine
    container_name: api-opovo-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - api-opovo

networks:
  api-opovo:
    driver: bridge